version: '3'
services:
  ssh-honeypot:
    image: 'local/ssh-honeypot:latest'
    build:
      context: .
      args:
        UID: $UID      
    ports:
      - '6346:2022'
    volumes:
      - $LOG_DIR:/home/honeycomb/log
      - rsa:/home/honeycomb/rsa     
    networks:
      default: 
    restart: unless-stopped

volumes:
  rsa:
    driver: local

networks:
  default:
